services:
    nginx:
        build: 
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - ./app/:/var/www/html/

    php:
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./app/:/var/www/html/

    mysql:
        image: mysql:8.0.33
        ports:
            - "3306:3306"
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: userdev
            MYSQL_PASSWORD: passdev
            MYSQL_DATABASE: test_db
            MYSQL_TCP_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/sql:/docker-entrypoint-initdb.d
            - ./docker/sql/conf.d:/etc/mysql/conf.d
